<?php

return[
        "Asciugacapelli",
        "Acqua calda",
        "Rondella",
        "Essenziali",
        "Appendini",
        "Lenzuoli",
        "Cuscini e coperte extra",
        "TV",
        "Camino da interno",
        "Il riscaldamento",
        "Allarme antincendio",
        "Allarme monossido di carbonio",
        "Estintore",
        "Kit di pronto soccorso",
        "Wifi",
        "Allarme antincendio",
        "Allarme monossido di carbonio",
        "Estintore",
        "Kit di pronto soccorso",
        "Cucina",
        "Frigorifero",
        "Microonde",
        "Nozioni di base sulla cucina",
        "Stoviglie e posate",
        "Lavastoviglie",
        "Fornello",
        "Forno",
        "Caffettiera",
        "Lungomare",
        "Ingresso privato",
        "Patio o balcone",
        "Giardino dietro la casa",
        "Griglia per barbecue",
        "Kit di pronto soccorso",
        "Parcheggio gratuito in loco",
        "Vasca idromassaggio privata",
        "Animali ammessi",
        "Consegna bagagli consentita",
        "Permessi soggiorni di lunga durata",
        "L'ospite ti saluta",
        "Pulizia prima del check-out",
        "Parcheggio gratuito in loco",
        "Vasca idromassaggio privata",
        "Parcheggio gratuito in loco",
        "Vasca idromassaggio privata",
        "Parcheggio gratuito in loco",
        "Vasca idromassaggio privata",
]



?>